"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ref_1 = require("./ref");
exports.useRef = ref_1.useRef;
exports.isRef = ref_1.isRef;
var component_1 = require("./component");
exports.defineComponent = component_1.defineComponent;
var page_1 = require("./page");
exports.definePage = page_1.definePage;
var inject_1 = require("./inject");
exports.provide = inject_1.provide;
exports.inject = inject_1.inject;
var watch_1 = require("./watch");
exports.watch = watch_1.watch;
var computed_1 = require("./computed");
exports.computed = computed_1.computed;
